environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.11"
    - nodejs_version: "4.0"
    - nodejs_version: "4.1"
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"

platform:
  - x86
  #- x64

version: "{build}"

build: off

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - cmd: npm test
